project:
  type: book

book:
  title: "emotions: Ally Or Enemy"
  subtitle: "emotions, will be your most powerful ally or your most dangerous enemy, 2nd edition"
  author: "emotiony.io"
  date: "12/6/2023"
  page-navigation: true
  reader-mode: true
  favicon: images/logo.png
  twitter-card: true
  back-to-top-navigation: true
  site-url: https://book.emotionuy.io
  repo-url: https://github.com/emotionysand/emotionsAllyOrEnemy
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - contents/foreword.qmd
    - contents/intro.qmd
    - part: "Part I: Pain Exists"
      chapters:
        - part1/PainExists.qmd
        - part1/DestructiveEmotions.qmd
        - part1/BreakBadHabit.qmd
    - part: "Part II: You can win"
      chapters:
        - part2/YouCanWin.qmd
        - part2/LevelsEnergy.qmd
        - part2/Psychomagic.qmd
        - part2/TheWork.qmd
        - part2/PowerNow.qmd
        - part2/SilvaMethod.qmd
        - part2/MindValley.qmd
        - part2/HappyMoney.qmd
        - part2/Meditation.qmd
        - part2/Lateralization.qmd
    - part: "Part III: Or Die"
      chapters:
        - part3/OrDie.qmd
        - part3/InnerCulture.qmd
        - part3/OuterCulture.qmd
        - part3/Identity.qmd
    - part: "Part IV: So, Action"
      chapters:
        - part4/SoAction.qmd
        - part4/Rules.qmd
    - contents/emotiony.qmd
    - contents/summary.qmd
    - contents/references.qmd



format:
  html:
    cover-image: images/cover.png
    theme: 
      light: cosmo
      dark: superhero
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  epub:
    cover-image: images/cover.png



