project:
  type: book

book:
  title: "emotions: Ally Or Enemy"
  subtitle: "emotions, will be your most powerful ally or your most dangerous enemy"
  author: "emotiony.io"
  date: "12/6/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - chapter_01.qmd
    - chapter_02.qmd
    - chapter_03.qmd
    - chapter_04.qmd
    - emotiony.qmd
    - references.qmd



format:
  html:
    theme: cosmo
  epub:
    cover-image: cover.png



