
# Chapter#4: So, Action

"It is the same with people as it is with riding a bike. Only when moving can one comfortably maintain one’s balance."

This well-known quote from Albert Einstein reflects faithfully how your brain works: if you cease on your work to terminate negative emotions, then multiple and new forms of destructive emotions will emerge with new variations of old ones.

This process will reinforce old patterns and painbody (inner and outer culture) and its power over you and your identity will eventually gain the dark side that painful lives perfectly know.

On the contrary, more work, more constructive emotions you get, the prize undoubtedly worths it. Decision making is key in this equation and it can not set aside.

If you feel a huge amount of energy is draining from somewhere, stop and go deep to the roots, and then, take action.

Taking action will come with this pack, I assure you:

It will very painful and blocking, it will hurt like hell: do not run away, 
it will take a long time from decision making to take action until it is fully solved: do not hurry up,
it will very difficult and tough: do not give up. Rest some time, but do not give up.


Life is not a picnic and you are not a girl or a boy, right? If you feel so bad, you are on the right path. Feeling bad is a fundamental part of being an adult. Choose the right tool. Work. That is all. Take action.

If instead, you do not feel a huge amount of energy is draining but there is some fog and discomfort around you, then, there is a solution: take action!

Whatever it happens, the main idea is easy:
if your doubt is between doing either not-doing, always choose to do. 

I will repeat and explain the idea if you are stuck, doubtful and questioning both sides of the question and it is not clear. Stop thinking. Between doing either not-doing, always choose to do. Because:

If it goes right, save yourself that useless thinking time,
If not, you will learn, remember, fail fast, life is not a picnic.

If you feel that fog, somehow discomfort, some bad feelings but nothing more, your must go, take action and work, exercise, run, sing, write and whatever you do through that discomfort: do whatever you do with discomfort. I promise you that action will kill it. Therefore, to solve the problems that negative emotions carry  you need:

Energy, you have it, you are alive. Use it to grow inner peace killing negative emotions by understanding them.
Tools, read this book. 
Action (discipline and focus). Life is not a picnic and you are an adult. Forget Disneyland now. So, action!

If not you will not feel emotions, but that fake that hide real emotions, real pain and real inner peace. You will live with that mental fog which chains you to negative emotions.

You will live sentimentality, in full self-deception, in false comfort.

Identity loves to splash around in the shit thinking it is real life, but no. Remember, you are moving without pedalling and life feels good, but it means you and your bike are mountains down .. backwards. Is it necessary that I explain how it finishes?

How to differentiate  real emotions from sentimentality? Easy, you, your identity and your life change. Once you feel it, never forge. Life is unforgettable. 

There are several rules you may apply from science which will reinforce your quest and allow to  concentrate all your energy in growing faster, stronger, smarter and richer.

These general rules are a straightforward way to gain more constructive emotions and make them your most powerful ally. 

"Life Is Like Riding a Bicycle. To Keep Your Balance You Must Keep Moving"
albert einstein

With these rules, you will obtain more power, but remember, this power comes with new changes and negative emotions. You are riding the bike of your life, keep pedalling. These general rules are:
 
Diet/Sugar, Sleep, Cold Shower
Conversations/People, Media, University 
Meditation, Exercise/Sex, Sun
Write it down, focus, work creativity

If you can not, evaluate what you are not doing and why. That is, a lack of purpose? Why? Family? Painbody? Fear? Fear of what? Write it down, read, work, change. Choose a convenient tool for each moment.

General Rules to get action (I)
Diet/Sugar, Cold Shower, Sleep


I will quote Ben Greenfield to close that topic as soon as possible: "43 Reasons That Sugar Destroys Your Health." It is 100% that sugar kills you, kills your health and destroys all your energy. Adds lots of frog to your mind and the long list you may consult.
It is no brain. Stop sugar forever, you are feeding negative emotions. And, as an example, sugar can suppress your immune system and upsets the mineral relationships in your body. And the same goes for fast food...

Another time fighting against comfort, cold shower: this challenge (as an example of 21 days program) will up your energy levels.

Here's how it works: during this 21 Day Cold Shower Challenge, tap into all the health, performance, metabolism and sexuality benefits cold thermogenesis can give you. The challenge is quite simple.
 
Follow the work of Wim Hof with cold habits: it will save your  life and will top your energy levels.

General Rules to get action (I)
Diet/Sugar, Sleep, Cold Shower

Here you have a lot of resources to understand how sleep works. Circadian rhythms are biological processes linked to the cycles of the day. Many bodily functions vary according to these rhythms, including the following:

Body temperature.
Pulse rate and blood pressure.
Reaction time and performance.
The production of melatonin, serotonin, and cortisolIntestinal activity

Light directly affects the production of melatonin, the so-called “hormone of darkness”, which is secreted mostly by the pineal gland during the hours of darkness. Melatonin plays a crucial role in the regulation of the sleep-wake cycle. Melatonin, among other things, promotes sleep and affects sleep quality.
It is very important to track regularity, same timetable and hours and understand how brain wave patterns work. 

General Rules to get action (II)
Conversations/People, Media, University


This chapter of general rules is very easy to understand and very difficult to follow. You must remember that your inner peace and energy are very fragile and limited. Do not waste what you do not have in abundance and is a precious treasure.

Do not waste your time in useless conversations with people. It will take from you a lot of energy and inner peace and, instead, you will carry back new negative emotions. Bad business.

Avoid from now all media and social network that adds negative emotions to you and work in yourself. A day has got 24h long, take profit to do, to learn and not to feed negative emotions.

Be careful where you invest your money and time. Remember, do not permit college interposes between you and your education. Perhaps if you are looking for real education University is not the right place.

General Rules to get action (III)
Meditation, Exercise/Sex, Sun

5 days of meditation practise with the integrative body–mind training method shows significantly better attention and control, showed greater improvement in conflict scores on the Attention Network Test, lower anxiety, depression, anger, and fatigue, and higher vigour on the Profile of Mood States scale, a significant decrease in stress-related cortisol, and an increase in immunoreactivity. It is clear, make mediation part of your daily routine.

Tabata training was discovered by Japanese scientist Dr Izumi Tabata. 
High-intensity interval training has a high impact on both the aerobic and anaerobic systems so five to ten minutes of daily routines are enough. 
Each exercise in a given Tabata workout lasts only four minutes, but it's likely to be one of the longest four minutes you've ever endured. The structure of the program is as follows:
Work out hard for 20 seconds
Rest for 10 seconds
Complete 8 rounds

About sex: practice it, avoid masturbation, it drains a lot of energy.

You need 10 to 20 minutes of sun daily. Do it. No excuses.

"All streams flow to the sea because it is lower than they are.
Humility gives it its power.
If you want to govern the people,
you must place yourself below them.

If you want to lead the PEOPLE,
you must learn how to follow them.

The Master is above the PEOPLE, And no one feels oppressed.
She goes ahead of the people,
and no one feels manipulated.
The whole world is grateful to her.

Because she competes with no one,
no one can compete with HER." 

TAO TE CHING, by Lao Tzu,  Translated by Stephen Mitchell

General Rules to get action (IIII)
Write it down & work creativity, focus

Writing down your goals and dreams have such a profound impact and it is a health weekly routine you should evaluate. The explanation has to do with the way our brains work and how to process emotions and thoughts. As you may know, the corpus (the wide, flat bundle of neural fibres) that connects the two hemispheres is the conduit through which the electrical signals between the right brain, which is imaginative, and the left brain, which is logical, make contact. These electrical signals then move into the spinal column, then communicate with every fibre, cell and bone in our body. It allows us to align our frequency to a life we would love living.
So, if you just think about one of your goals or dreams, you’re only using the right hemisphere of your brain, which is your imaginative center. But, if you think about something that you desire, and then write it down, you also tap into the power of your logic-based left hemisphere. And you send your consciousness and every cell of your body a signal that says, “I want this, and I mean it!”

Avoid media and mobile, avoid distractions and train your focus. Without it, it can not possibly work and get the things done. Work in a quiet environment without interruptions.