
# Chapter#1: Pain exists

The National Science Foundation release time ago this shocking number, an average person has about 10,000 to 60,000 thoughts per day. Of those, 80% are negative and the most, almost 100% are repetitive ones. Well, perhaps the number is inaccurate, let's say it is 25,000, highly enough? 

Those thoughts are creating an imaginary and brutal drama in your mind. These repetitive thoughts are creating a negative pattern and but still, they are triggering an entire universe of emotions related to each thought: it would be amazing if it were not terrible.

Remember, if you are not aware of them, they will stop whispering and start shouting. They will grow until collapse your life, health either wealth, probably both of them.  

The list is endless: fears, trauma, insecurities, present, past and future losses, failures, broken hearts and more and more fears.

Your lack of awareness of this process is literally feeding a living organism within your mind who is colonizing your brain, your health, your body and finally your wealth.

When this happens the consequences are known. No more energy for sex, or creativity. No more ideas to create a start-up, quit your boring job or love your family. Your entire life and energy goes to this organism: the pain-body.

It shapes your identity so far and you will eventually die for it. Your life will hopelessly bend to this side, suddenly you will see that your external life reflects your internal mind. Your day-by-day life will mirror your mind and it will not be a surprise that all your friends share their negative thoughts and failures with you.

Then, your conversations will turn about sad stories, bad things and dark futures. You are feeding the inner monster, no healthy diet, no more exercise, no more sex, no more right sleep, no more creative job.

You did it and your inner energy is not unlimited: you choose between feed your inner monster either your inner peace. Yes, I understand that inner peace concept is boring but each minute you give it to your inner gang, you take it from your life. From your peace. Literally.
 
"Watch your thoughts;
they become words. Watch your words;
they become actions. Watch your actions; they become habit. Watch your habits;
they become character.

Watch your character;
it becomes your destiny.”ç

lao tzu

As Dalai Lama and Daniel Goleman say "Distinguishing between constructive (positive) and destructive (negative) emotions is right there to be observed in the moment when a destructive emotion arises-the calmness, the tranquility, the balance of the mind is immediately disrupted. Other emotions do not destroy equilibrium or the sense of well-being as soon as they arise, but in fact enhance it, therefore would be called constructive."

Thus, when destructive emotions arise your inner energy vanish for log as it is fueling that negativity. We call destructive because they are destroying you. Positive emotions boost construction, therefore, creativity and new worlds emerge. 

So, emotions are your most inner and deep enemy, if you do not hear them.

And, sure, emotions, as a living organism (pain-body) may create struggle because this dark power feedbacks your thoughts as well and as a consequence your actions which are soaring on those previous emotions and will create new destructive emotions and thoughts, and so, new actions, and so on.

You see. You are in serious trouble, inside a hurting cycle.

This repetitive cycle, this repetitive emotions and thoughts create a solid pattern in your brain. Your are rewiring your brain to this. Creating something really physical, real and strong. You are delivering all your energy to that rewiring.

Call it identity. Call it destiny. Call it bad luck. Call it struggle.

That is struggling when you, as an exemple, rise a start-up (from "The Hard Thing About Hard Things: Building a Business When There Are No Easy Answers"). The struggle is when:

You wonder why you started the company in the first place and people ask you why you don’t quit and you don’t know the answer.
When your employees think you are lying and you think they might be right. Besides, you don’t believe you should be CEO of your company and you are in over your head and know you can’t be replaced.
When everybody thinks you are an idiot, but nobody will force you. Self-doubt becomes self-hatred.
You are having a conversation with someone and you can’t hear a word they are saying because all you can hear is the struggle and furthermore, you are surrounded by people and you are all alone.
You go on vacation to feel better and you feel worse and food loses its taste.


So, here we have set the problem,
maybe you have risen a family, or perhaps a start-up or a bright endeavour: you are in the creative arts and your are writing a book or acting in an important movie. Maybe you are in science or healing someone.

Something pushed you in the past to this quest and now you can not anymore.

"It is not uncommon for people to spend their whole life waiting to start living."

EKHART TOLLE

But now, there is no energy to execute things. Negative emotions are devorating it when you are not watching out.

No motivation. No vision. No future.

Just repetitive days as your repetitive thoughts. And destruction and negative emotions are growing and growing and your health and wealth decreasing and flattening.

And repetitive behaviour: hiding from tasks and duties. The little ones are the worst.

Here is the fundamental problem: people think of execution of a task as the little side of the business or the boring part of jobs, something you should delegate while you focus on the perceived “bigger” issues or something more creative and relevant.

This idea is completely wrong. Execution is not just tactics—it is a discipline and a system. It is the most important thing. It is not a goal. It is the now.

It is the habit: doing. Living. Execute it. Action. Do it. Now. No excuses.

You just already knew. The little details of a job are as important as the big ones, like being present with your kid to play with toys.

Execution is not only the biggest issue facing life today; it is something nobody has explained satisfactorily. And the reason is that all your energy is draining on that pain-body. And you have left nothing.



And, for sure, this pattern which creates all the things that surround you, this is, friends, jobs, habits, health, wealth. It is also creating your future and recreating your past.

It is the way the brain works. It drives you and you feed it with your life. You are hijacking yourself.

You know perfectly that place, where there is no freedom and always there are no options to choose. But nobody takes you to that place except you: repetitive thoughts and emotions sculpt your body. You body reflects you. Your skin reflects you.

Emotions signs, they help, the may be your ally or your worst enemy. So far, bad news. Now, the good news is coming: thoughts and body are key and will help you to solve this struggle. This pain.

