# Introduction {.unnumbered}

Life is a journey through emotions since the first light in the morning to the darkest sunset breaking the night. It is the most powerful force and at the same time, it may block all the inner fire of an empire.

That is it, likewise, emotions are not at the origin of nothing, it is our most perverse misconception of everything, it is where all your suffering, procrastinating and no sense emerge at every moment of your life.

## Where is the origin?

The origin, no doubt, for millennia is these three mental states[^1] (how we perceive the world):

- **Confusion** (welcome to the internet, yes, with the clarity goes the darkness).
- **Hatred** (welcome to twitter, and time to time there are some accounts where enlightenment pours wisdom).
- And **greed** (welcome to LinkedIn, money and sex always travel together).

:::{.callout-note}
## Fatal Misconception
This wicked and fatal misconception of reality not only destroys your life (within the swirl of negative emotions) but also pushes you to the poorest mental state of all: 

being a kind of zombie who wait for a bus that will never come and leave your life in an eternal stand-by.
:::


So, how may an emotion do help us to solve this chaos and mess if emotions are not the origin of nothing?

## Blue and Red pill

How? Well, two clearways are open wide ahead in front of you in this ebook and you are going to skyrocket your life's top now and forever understanding how they work and using the tool kit we are going to provide you:

<mark>Negative emotions signs where the problem is.  
Cope with the non-emotion state.</mark>


Negative emotions **signs where the problem is**. It is the most important clue you would ever have and the place where you should start your work. Negative emotions are nice but uncomfortable. They sign. They do the most difficult job: the first step. They work! You only have to notice them, be aware when they arise, that is simple but not always easy.

This ebook contains the entire tool kit. Enjoy it!

Love negative emotions because they pave your way to success: to be who you really are (a fucker, carpenter, a billionaire, or the next Elon Musk).

<mark>Transform negative emotions from enemy to ally.</mark>

Do it now, and every day. As your best habit, not as a goal, but as your inner warrior who feeds you with inner peace: the place where things really happen and all start and die. The place where unlimited creativity and never imagined force are. Discover who you really are. Enjoy the journey!

On the contrary, positive emotions confirm you are on the right way, but you already knew this, and it is irrelevant, we are not here to feel emotions, we are here to showcase.

## Blue pill

<mark>The blue pill is your choice to ignore or suppress negative emotions.</mark>

It advises against listening to those emotions, feeding into them, following them, or believing them. Taking the blue pill is a bad idea as it transforms you into a "zombie," implying a state of numbness or lack of self-awareness.

By embracing and transforming negative emotions into allies, one can pave the way to success, discover their true self, and tap into unlimited creativity and inner strength. Positive emotions are secondary to this path of self-discovery and growth.

## The Path, Do The Work

Then, the point is how to use the non-emotional state as an ally and not as an enemy.  When subtle emotions hide behind an action and confuses us. Destroy them. Do it.


> When a thought hurts, that is the signal that it is not true.  
>
> -- Byron Katie


This ebook will provide you with the tools and the gems of millenia packed in a very simple and concise way, straight forward to you in four parts:

1. **Pain exists**, negative emotions are there, add this is not bad news, it is just the way it is. Emotions are the last reaction, when something happens: they just inform you whispering. If you hear their message, you will take action. If not, new more powerful emotions will rise until they finally get your attention. 
2. **You will win**, no way. Here is the how. Embrace it now. Learn.
3. **Or die**. Die in the best possible way: kill your old identity, leave her/him alone and allow the new one emerge. Keep your life alive. Or die waiting the bus: be a zombie.
4. **So, action!** Not tomorrow, but now!

[^1]: [What are the three poisons? (Greed, hatred, and delusion)](https://tricycle.org/beginners/buddhism/three-poisons/){.external}