
# You can win

Nowadays we may access to millennia wisdom easily but as well we can read authors and thinkers who are creating a new set of tools and skills that will help you for sure; texts written with the modern and tech world we live in mind.

Here comes the set of tools which will be central to solve all the questions previously spoken.

There are a lot of diverse tools you can use. They are not theoretical, they are 100% practical and provides you with a lot of exercises that fit with your needs.

In fact, it is necessary the existence of this diverse amount of tools, skills and approaches because it applies to all the connections where emotions operate and evolve.

As we have seen, emotions are part of a human complex system design to relate to reality (and people). Emotions are central in this system of perception (body), mind (thoughts and how thoughts are processed, as symbolism or language) and higher mind (altered states).

"Greatness is the courage to overcome obstacles."
david hawkins

These tools, books, authors, methods and techniques are:

How to understand emotions (destructive-constructive) links with the different levels of energy: Levels Of Consciousness, by David Hawkins
How our mind works in different levels of symbolism and not rationally at all: Psychomagic, by Alejandro Jodorowsky
How our beliefs and thoughts generate our destructive emotions: The Work, by Byron Katie
Our body and others portals as gateway and the painbody, The Power of Now by Eckhart Tolle
How to use our creative mind and access to high states: Altered states by Jose Silva
How emotions cope with money issues, Happy money by Ken Honda
How to hack out mind from modern view: MindValley and The code of the extraordinary mind by Vishen Lakhiani
How to understand meditation: Meditation, by Yongey Mingyur Rinpoche

Levels of Emotions-Energy, 
the Hawkins scale of energies frequency 


The inner concept with this framework is that as we walk up, that is, you grow by experience, the ladder of consciousness, you shift energy from a very basic place where there are just satisfaction and lots of pain (destructive and negative emotions) to a very higher place which is plenty of personal fulfilment and positive external impact (constructive and positive emotions).

Undoubtedly, there is a path, a ladder, an open and plain way that facilitate you your hard-working to understand what is going on. The negative emotion in this framework is a deeper bond with a level of energy and its output. So, it is relatively easy to understand and connect emotions-energy-actions and pain.

This framework examines “energy” and associates numerical values to the different levels of negativity-positivity from which you operate. It is pretty obvious that with high levels of energy and positivity your actions will be powerful, consistent and very defined. Thus, to relate positive emotions to constructive action is a very natural link.

Certainly, these levels of energy are hardly manifested as pure states in you. You may be at a state of energy, let’s say with work, that may be different than where you are at in love. Either, you may have reached a higher state of energy, with lots of positive emotions and constructive actions and at moments, temporarily, return to a lower level depending on different external conditions.

"When I was 17, I read a quote that went something like:

'If you live each day as if it was your last, someday you’ll most certainly be right.'

It made an impression on me, and since then, (...), I have looked in the mirror every morning and asked myself:

'If today were the last day of my life, would I want to do what I am about to do today?’

And whenever the answer has been 'no' for too many days in a row, I know I need to change something."

STEVE JOBS

However, this framework is a helpful tool for understanding what drives your behaviour. And, negative emotions sign you where you are: knowing the place you are is a high value-asset, it says where to start.

This framework works like this, from lower levels of energy to high levels of positive and constructive emotions (from "Power and Force"): 

Inaction

Shame – the level of Shame is perilously proximate to death, which may be chosen as conscious suicide or more subtly elected by failure to take steps to prolong life, as in “passive suicide.” 
Guilt, in a variety of expressions, such as remorse, self-recrimination, masochism, and the whole gamut of symptoms of victimhood. 
Apathy – This level is characterized by poverty, despair, and hopelessness. The world and the future look bleak; pathos is the theme of life. Apathy is a state of helplessness; its victims are needy and lack not only resources but also the energy to avail themselves of what resources may be available.
Grief – This is the level of sadness, loss and despondency. Most humans have experienced it for periods, but those who remain at this level live life in constant regret and depression. 
Fear – At this level there is a lot more life energy available; fear of danger is actually healthy. Fear runs much of the world. Fear of enemies, of old age or death, of rejection, and a multitude of social fears are basic motivators in most people’s lives.

Hyperactivity: 

Desire – Desire moves us to expend great effort to achieve goals or obtain rewards. The desire for money, prestige, or power runs the lives of many of those who have risen above Fear as their limiting, predominant life motif. Desire is also the level of addiction, where in desire becomes a craving more than life itself. 
Anger – Anger can lead to either constructive or destructive action. As people move out of Apathy and Grief to overcome Fear as a way of life, they begin to want; Desire leads to frustration, which in turn leads to Anger. Thus, Anger can be a fulcrum by which the oppressed are eventually catapulted to Freedom. But Anger expresses itself most often as resentment and revenge and is, therefore, volatile and dangerous.
Pride – People feel positive as they reach this level, in contrast to the other lower energy fields. This rise in self-esteem is a balm to all pain experienced at lower levels of consciousness. Pride looks good and knows it; it struts its stuff in the parade of life. Pride as such generally has a good reputation and is socially encouraged, yet as we see from the chart of levels of consciousness, it is sufficiently negative to remain below the critical level of Courage. 

Hapiness and Productivity:

Courage –  At the level of Courage, an attainment of power occurs; therefore it is also the level of empowerment. This is the zone of exploration, accomplishment, fortitude, and determination. 
Neutrality – At the Neutral level, a person can say, “Well, if I don’t get this job, then I’ll get another.” This is the beginning of inner confidence; sensing one’s power, one is therefore not easily intimidated. One is not driven to prove anything. 
Willingness – This very positive level of energy may be seen as the gateway to the higher levels. Whereas, for instance, jobs are done adequately at the Neutral level, at the level of Willingness, work is done well and success in all endeavors is common. 
Acceptance – At this level of awareness, a major transformation takes place, with the understanding that one is oneself the source of and creator of the experience of one’s life.

Peak perfomance without stress:

Reason – At this level one is capable of handling large, complex amounts of data; making rapid, correct decisions; understanding the intricacies of relationships, gradations, and fine distinctions; and expert manipulation of symbols as abstract concepts, which becomes increasingly important.

Synchornicy and extraordinary outcomes:

Love – Love is not intellectual and does not proceed from the mind. Love emanates from the heart. It can lift others and accomplish great feats because of its purity of motive. At this level of development, the capacity to discern essence becomes predominant; the core of an issue becomes the center of focus. As Reason is bypassed, there arises the capacity of recognition of the totality of a problem and a major expansion of context, especially regarding time and process. 
Joy –  As Love becomes more and more unconditional, it begins to be experienced as an inner Joy. This is not the sudden joy of a pleasurable turn of events; it is a constant accompaniment to all activities. Joy arises from within each moment of existence, rather than from any external source. This is a level of healing and tapping into ones spirituality.  Things happen effortlessly, by synchronicity, and the world and everything in it is seen to be an expression of love and Divinity. 
Peace – This level of consciousness is associated with the experience designated by such terms as transcendence, self-realization, and God-consciousness. Not uncommonly, individuals at this level remove themselves from the world, as the state of bliss that ensues precludes ordinary activity. Some become spiritual teachers; others work anonymously for the betterment of mankind.
Enlightenment – This is the level of powerful inspiration. Those that operate at this level set in place attractor energy fields that influence all mankind down through the ages.

This framework defines five groups of destructive-constructive emotions or levels of energy-consciousness, that is, from low to high:

Inaction,
Hyperactivity,
Hapiness and productivity,
Pak perfomance without stress
Synchronicy and extraordinary outcomes.


As you see, it is evident how negative emotions generates inactions and how positive ones allow you to create the best outcomes. The positive and constructive emotions are your best ally. Use them. (Image from @thebigwhisper)

Pyschomagic,
custom poetic acts work symbolically


This highly practical and creative tool shows how psychological realizations can cause real transformation when manifested by concrete and custom poetic acts designed symbolically.

While living in Mexico, Alejandro Jodorowsky became familiar with the eccentric but effective cures provided by folk healers and how emotions and thoughts were interwoven with deep mental pain expressed as a disease. Your mind represents symbolically that pain produced by destructive emotions. In that point, it is blatant the power of destruction tha destructive emotions hold and how well the name "destructive emotions" is asigned.

As a result, it is easier for the unconscious to understand the language of dreams than that of rationality. Illness can even be seen as a physical dream that reveals unresolved emotional and psychological problems.

Psychomagic presents the shamanic and genealogical principles to create a healing therapy that could use the powers of dreams, art, and theater to empower you to heal wounds that in some cases had traveled through generations.

The concrete and often surreal poetic actions are part of an elaborate strategy intended to break apart the dysfunctional persona with whom you identify to connect with a deeper self.

That is when real transformation can manifest and heal the painbody, heal the negative and destructive emotions that block your life and get stuck and trapped in that dark point where emotions are you worst enemy and drain all your energy into more pain.

Therefore, there is no space for big constructive emotions, thus psychomagic may be the real key to unblock those negative emotions, understand their origin and, eventually, wipe out its power over you. 

Psychomagic takes the same elements associated with a negative emotional charge and recasts them in an action that will make them positive and enable them to pay the psychological debts hindering their lives.

“Birds born in a cage think flying is an illness.”
Alejandro Jodorowsky

Metagenealogy is a practical guide, a very useful tool, to recognizing and overcoming the patterns of negative and profound desctructive emotions and influences of the four generations before you. It explains the way how this particular and inherited painbody comes from the past and survives to the future being an organism within your mind that shapes your world's perception. The tool's goal is to uncover your family’s psychological heritage, heal negative emotion patterns of behavior and illness in your family tree, and let positive emotions emerge.

It explains how you are the result of several sorroundings pushing you: repetition of familial patterns from the past (negative emotions and painbody), the creation of new ideas from postive emotions from inner peace and society rules and punishments constraining you executed by family. 

It is an embodied sense of self that you inherit from at least four prior generations, constituting both a life-giving treasure and a deadly trap. You are both an heir of your lineage and a necessary variation that brings the family into new territory. Are you doomed to repeat the patterns of your parents and grandparents? Or can you harness your familial and individual talents to create your own destiny?

The Work
if a thought hurts, question it. How? Do your Work


The core idea where the work rests is very simple but powerful: when you believe your thoughts you suffer, but when I do not believe them you do not suffer, and that this is true for every human being. Freedom is as simple as that. Upon this idea you can access to a very usefull tool of self-inquiry known as “The Work”.

All the negative and suffering generated by ideas and the related destructive emotions that goes on inside our minds is not reality. It’s just a story we torture ourselves with. The Work is a simple, completely replicable system for freeing ourselves of the thoughts and emotions that make us suffer. All war begins on paper, the war against those ideas and believes that drain your positive and constructive energy, for this reason, those ideas are the target of our war. 

A thought is harmless unless we believe it. It’s not our thoughts, but our attachment to our thoughts, that causes suffering. Attaching to a thought means believing that it’s true, without inquiring. A belief is a thought that we’ve been attaching to, often for years.

This tool is very easy to execute. You write down your stressful thoughts, and then ask yourself the following four questions.

Question 1: Is it true?
This question can change your life. Be still and ask yourself if the thought you wrote down is true.

Question 2: Can you absolutely know it’s true?
This is another opportunity to open your mind and to go deeper into the unknown, to find the answers that live beneath what we think we know.

Question 3: How do you react—what happens—when you believe that thought?
With this question, you begin to notice internal cause and effect. You can see that when you believe the thought, there is a disturbance that can range from mild discomfort to fear or panic. Make a list, and be specific.

Question 4: Who would you be without the thought?
Imagine yourself in the presence of that person (or in that situation), without believing the thought. How would your life be different if you could not even think the stressful thought? How would you feel? Which do you prefer—life with or without the thought? Which feels kinder, more peaceful?

Turn the thought around
The “turnaround” allows you to experience the opposite of what you believe. Once you have found one or more turnarounds to your original statement, you are invited to find at least three specific, genuine examples of how each turnaround is true in your life.

The power of Now,
how stillness stops train of thoughts mind


Now, this new set of tools sign directly to the present moment, that is, do not allow your mind to travel to past and future and focus the now, the present moment. If your mind vagues a creates out of the present, your negative emotions would rise without control. Even with repetition or the culture of your enviroment it may create a pattern of thoughts-emotions.

Finally, it will avoid you to be present and having the amount of necessary energy to focus at the present moment and properly execute minor task or be creative. 

There is such a thing as old emotional pain living inside you. It is an accumulation of painful life experience that was not fully faced and accepted in the moment it arose. It leaves behind an energy form of emotional pain. It comes together with other energy forms from other instances, and so after some years you have a painbody, an energy entity consisting of old emotion. That is the painbody.

Eckhart Tolle's message is simple and strigthforward: living in the now is the truest path to positive emotions and fullfilment. And some several tools and portals help you to understand negative emotions. Basicly, the main idea is to stop the stream of thoughts in your mind using the different aproch of every tool, that is, a portal to silence, portals to review those destructive emotions and understand them.

The body, as an exemple, is an excelent portal to now: using your inner body as an anchor to the Now.
The gift of full attention and the power in the simple act of noticing

Besides defining what painbody exactly is this tool adds what painbody is concealing: your life's purpose (next lines are adapted from "The power of Now").

If you look within rather than only without, however, you discover that you have an inner and an outer purpose, and since you are a microcosmic reflection of the macrocosm, it follows that the universe too has an inner and outer purpose inseparable from yours.

The outer purpose of the universe is to create form and experience the interaction of forms—the play, the dream, the drama, or whatever you choose to call it.

Its inner purpose is to awaken to its formless essence. Then comes the reconciliation of outer and inner purpose: to bring that essence—consciousness—into the world of form and thereby transform the world.

The ultimate purpose of that transformation goes far beyond anything the human mind can imagine or comprehend.

To produce constructive emotions you need to clarify your inner and outer purpose; name it a vision, a big goal. Rise a family or start a company, but the lack of purpuse leaves you alone without shield in front of a lot of negative emotions produced by the absence of direcction.


José Silva
silva method and alpha and altered state


José Silva was an electronics repairman who developed the formerly known as Silva Mind Control. Silva did research on the brain and various brain frequencies, this tool aims to reach and sustain a state of mental functioning, called alpha state, where brainwave frequency is seven to fourteen Hz: daydreaming and the transition to sleeping are alpha states.

With this tool, you will gain powerful positive and constructive solid emotions and habits and overcome negative emotions and its consequences (painbody, habits). It opens to increase your level of energy, free yourself from negative beliefs and behaviours, boost your creativity even learn to practise creative dreaming and awake intuition and inspiration.

The alpha brain state is active at your right hemisphere. You are in this state every day several times and it crucial understand how it works:

Every morning when you wake up (your mind passes from the theta brain state to the alpha and then to the beta).
You can use this time window to train yourself in the Silva Method and induced your mind into trance.
It is very important to learn how to enter and leave this brain state.
And you need to understand the alpha state boundaries.


"The discovery that human intelligence can learn to function, with awareness, at altered levels of mind, will go down in history as the greatest discovery of mankind.

It is sure to change our concepts of psychology, psychiatry, mind, and the subconscious."
jose silva

First, you must exercise every morning, for about fifty days, and while you count backwards you have to look, behind your closed eyelids, slightly above, that is 20 degree above the horizon. It is known that the brain produces alpha brainwaves when having your eyes at this position:

For ten days count backwards from 100 to 1 at a 2 seconds pace.
For the next ten days count backwards from 50 to 1 at the same pace.
For the following ten days count backwards from 25 to 1.
For the next ten days count from 10 to 1.
For the last ten days count from 5 to 1.

Second, you have to develop your very detailed visualization skill creating an imagery tool like a mental big black TV where you will project your visualizations. You need to practise to develop your visualization skill to focus entirely at a mental movie and try that irrelevant thoughts do not interrupt. As an example, in case you meditate before sleeping, you just confirm that you are going to have a night of restorative sleep.

Third, this is a mental movie you are going to play on your big flat mental TV:

Think one negative emotion o problem you can not solve. Keep it for minutes.
Imagine it solves by a basic and general solution. Visualize it in detail.
Recreate how it feels when the problem disappears, how it affects your family, and all the positive emotins related.


Vishen Lakhiani and MindValley
know the code

You need to know the code, as a engineer and programmer, Vishen Lakhiani, provides you with powerful tools to understand our negative emotions and mindset and how destructive they can be in the tech world we live. 

This map guides you how to break the code and achieve extraordinary results in life.

First at all, our sorrounding culture may be a negative influence, that is, you must transcend the culturescape and question society’s bullshit rules.

As you move through life, you are constantly told what you should do or how you should live. Our culture contains many outdated beliefs that dictate what kind of job and education you should have and how you should think and eat. Or weather, as an exemple, you need a college degree to guarantee success. Maybe you do not need a degree at all. Maybe you are in the wrong way. Update your believe, question it.

Second, practice consciousness engineering and create self-encouraging models of reality. Thus, you may need to rewrite your models of reality updating your mindset, that is, redefining what you think about yourself and how this triggers negative emotions.

Third, upgrade your system for living and be able to bend reality. This will lead you to a three-step approach of discovering, refreshing and measuring.

So the first step is to discover, you can do this by reading books, talking to people and exploring the world around you for inspiration. As an example, check mindvalley.com, guarantee you will find out lots of inspiration and what inspiration is.
Second, refresh regularly.
Third, measure how effective you are being.

Re-coding your mindset to get the ability to bend reality. That  means that you can hold onto your goals for the future while making sure that your inner peace is firmly rooted in the present by focusing on the here and now: make fun and happiness a key part of your daily life. 

Fourth, practice blissipline and create a vision for their future. Blissipline starts with gratitude. It has been scientifically proven that people have more energy and experience less depression when they practice gratitude.
"The people making you feel guilty for going your own way and choosing your own life are simply saying, 

'Look at me. I’m better than you because my chains are bigger.'

It takes courage to break those chains and define your own life.

So dare to live your precious days on Earth to their fullest, true to yourself, with open heart and thoughtful mind, and with the courage to change what doesn’t work and accept the consequences.

You may find that you can fly farther than you ever imagined."

Vishen Lakhiani

Reverse the froward gap. The forward gap is the distance between your present self and who you want to be. But the problem with focusing on the forward gap is that you are always keeping positive emotions out of you reach in the future and creating negative ones. Never experiencing positive ones, instead, destructive emotions that destroy your execution day-by-day.

You should reverse the gap and look to your past to appreciate and be grateful for what you have achieved so far. This allows you to practice blissipline.

Crafting a vision is key for your future that corresponds with your inner peace. However, this vision can be dangerous if you confuse your vision with culturescape's vision.

Fifth, be unfuckwithable and embrace your quest. Your motivation for reaching your vision must come from within; do  not seek validation from outside.

Be unfuckwithable. This means realizing that you depend only on yourself and that nothing anyone says or does can stop you from achieving your goals by having self-fueled goals that aren’t dependent upon others and realizing that only you have what it takes to be successful. 

"It turns out that our brains are literally hardwired to perform at their best not when they are negative or even neutral, but when they are positive.

Yet in today’s world, we ironically sacrifice happiness for success only to lower our brain’s success rates"
Shawn Achor

Happy Money
powerful lessons from The Japanese Art of Making Peace with Your Money

There are so many emotions wrapped up in your money. Money may be stressful, but getting your finances in order may provide positive emotions instead of destructive ones. You may start to construct with a different approach to money. The practice here and useful tool is to tear apart the negative emotions which live next to money's concept. Once done, positive emotions emerge. 

If you are going to save money, save it while you imagine the many fun ways to spend it. Imagine it like this:

"First class flight to Bali with lie-flat seats, with a luxurious stay at the Four Seasons Sayan. Gourmet dinner, luxury accommodations, and several spa treatments."

“Want to be wealthy?” Happy? Peaceful?” Say, thank you. It’s that simple.” Try being grateful for the joys in your life and watch your mood brighten. Thank those who have helped you get to wherever you are and show appreciation to those who help you in the future.  You may be surprised at how much more money and help flow your direction.  Who do you owe a thank you to?

Meditation
joy of living, unlocking the secret and science of happiness


The Joy of Living is a path of meditation practice that is very easily to follow by you and focus in explaining it to modern world. Meditation is a key-tool to master emotions, to understand negative and positive emotions, it empower and sharpen your real intelligence. Ultimatly, it is an esencial tool to understand your own mind.

Meditation deals with basic functions of the mind and the movements toward inner peace and away from suffering.

The Joy of Living method contains three levels:

Calming the Mind
Opening the Heart
Awakening Wisdom


First, calming the mind, in this level you will use any situation or experience, included negative emotions and painbody, as a gateway to inner peace.

Second, you are meditating how to open your heart to the world around you and decrease the self-fixation that lies at the root of negative emotions.

Third, in this level you will practise the insight meditation, a profound form of meditation that uproots the causes of negative emotions.

The goals of this tool included:

How to rest in a state of spacious and alert presence using visual objects, sounds, tastes as support to transform negative emotions and painbody.
How to deal with distractions and understand daily meditation, postures, lenght and to define a session.
How negative emotions relate to fixate just in your wellbeing and positive mental states can grow.
How to see beyond superficial thoughts and emotions and see things as they actually are, rather the mistaken version of reality that we project onto the world.