
# Levels of Energy


Levels of Emotions-Energy, 
the Hawkins scale of energies frequency 


The inner concept with this framework is that as we walk up, that is, you grow by experience, the ladder of consciousness, you shift energy from a very basic place where there are just satisfaction and lots of pain (destructive and negative emotions) to a very higher place which is plenty of personal fulfilment and positive external impact (constructive and positive emotions).

Undoubtedly, there is a path, a ladder, an open and plain way that facilitate you your hard-working to understand what is going on. The negative emotion in this framework is a deeper bond with a level of energy and its output. So, it is relatively easy to understand and connect emotions-energy-actions and pain.

This framework examines “energy” and associates numerical values to the different levels of negativity-positivity from which you operate. It is pretty obvious that with high levels of energy and positivity your actions will be powerful, consistent and very defined. Thus, to relate positive emotions to constructive action is a very natural link.

Certainly, these levels of energy are hardly manifested as pure states in you. You may be at a state of energy, let’s say with work, that may be different than where you are at in love. Either, you may have reached a higher state of energy, with lots of positive emotions and constructive actions and at moments, temporarily, return to a lower level depending on different external conditions.

"When I was 17, I read a quote that went something like:

'If you live each day as if it was your last, someday you’ll most certainly be right.'

It made an impression on me, and since then, (...), I have looked in the mirror every morning and asked myself:

'If today were the last day of my life, would I want to do what I am about to do today?’

And whenever the answer has been 'no' for too many days in a row, I know I need to change something."

STEVE JOBS

However, this framework is a helpful tool for understanding what drives your behaviour. And, negative emotions sign you where you are: knowing the place you are is a high value-asset, it says where to start.

This framework works like this, from lower levels of energy to high levels of positive and constructive emotions (from "Power and Force"): 

Inaction

Shame – the level of Shame is perilously proximate to death, which may be chosen as conscious suicide or more subtly elected by failure to take steps to prolong life, as in “passive suicide.” 
Guilt, in a variety of expressions, such as remorse, self-recrimination, masochism, and the whole gamut of symptoms of victimhood. 
Apathy – This level is characterized by poverty, despair, and hopelessness. The world and the future look bleak; pathos is the theme of life. Apathy is a state of helplessness; its victims are needy and lack not only resources but also the energy to avail themselves of what resources may be available.
Grief – This is the level of sadness, loss and despondency. Most humans have experienced it for periods, but those who remain at this level live life in constant regret and depression. 
Fear – At this level there is a lot more life energy available; fear of danger is actually healthy. Fear runs much of the world. Fear of enemies, of old age or death, of rejection, and a multitude of social fears are basic motivators in most people’s lives.

Hyperactivity: 

Desire – Desire moves us to expend great effort to achieve goals or obtain rewards. The desire for money, prestige, or power runs the lives of many of those who have risen above Fear as their limiting, predominant life motif. Desire is also the level of addiction, where in desire becomes a craving more than life itself. 
Anger – Anger can lead to either constructive or destructive action. As people move out of Apathy and Grief to overcome Fear as a way of life, they begin to want; Desire leads to frustration, which in turn leads to Anger. Thus, Anger can be a fulcrum by which the oppressed are eventually catapulted to Freedom. But Anger expresses itself most often as resentment and revenge and is, therefore, volatile and dangerous.
Pride – People feel positive as they reach this level, in contrast to the other lower energy fields. This rise in self-esteem is a balm to all pain experienced at lower levels of consciousness. Pride looks good and knows it; it struts its stuff in the parade of life. Pride as such generally has a good reputation and is socially encouraged, yet as we see from the chart of levels of consciousness, it is sufficiently negative to remain below the critical level of Courage. 

Hapiness and Productivity:

Courage –  At the level of Courage, an attainment of power occurs; therefore it is also the level of empowerment. This is the zone of exploration, accomplishment, fortitude, and determination. 
Neutrality – At the Neutral level, a person can say, “Well, if I don’t get this job, then I’ll get another.” This is the beginning of inner confidence; sensing one’s power, one is therefore not easily intimidated. One is not driven to prove anything. 
Willingness – This very positive level of energy may be seen as the gateway to the higher levels. Whereas, for instance, jobs are done adequately at the Neutral level, at the level of Willingness, work is done well and success in all endeavors is common. 
Acceptance – At this level of awareness, a major transformation takes place, with the understanding that one is oneself the source of and creator of the experience of one’s life.

Peak perfomance without stress:

Reason – At this level one is capable of handling large, complex amounts of data; making rapid, correct decisions; understanding the intricacies of relationships, gradations, and fine distinctions; and expert manipulation of symbols as abstract concepts, which becomes increasingly important.

Synchornicy and extraordinary outcomes:

Love – Love is not intellectual and does not proceed from the mind. Love emanates from the heart. It can lift others and accomplish great feats because of its purity of motive. At this level of development, the capacity to discern essence becomes predominant; the core of an issue becomes the center of focus. As Reason is bypassed, there arises the capacity of recognition of the totality of a problem and a major expansion of context, especially regarding time and process. 
Joy –  As Love becomes more and more unconditional, it begins to be experienced as an inner Joy. This is not the sudden joy of a pleasurable turn of events; it is a constant accompaniment to all activities. Joy arises from within each moment of existence, rather than from any external source. This is a level of healing and tapping into ones spirituality.  Things happen effortlessly, by synchronicity, and the world and everything in it is seen to be an expression of love and Divinity. 
Peace – This level of consciousness is associated with the experience designated by such terms as transcendence, self-realization, and God-consciousness. Not uncommonly, individuals at this level remove themselves from the world, as the state of bliss that ensues precludes ordinary activity. Some become spiritual teachers; others work anonymously for the betterment of mankind.
Enlightenment – This is the level of powerful inspiration. Those that operate at this level set in place attractor energy fields that influence all mankind down through the ages.

This framework defines five groups of destructive-constructive emotions or levels of energy-consciousness, that is, from low to high:

Inaction,
Hyperactivity,
Hapiness and productivity,
Pak perfomance without stress
Synchronicy and extraordinary outcomes.


As you see, it is evident how negative emotions generates inactions and how positive ones allow you to create the best outcomes. The positive and constructive emotions are your best ally. Use them. (Image from @thebigwhisper)


[^1]: [](){.external}
[^2]: [](){.external}