
# The joy of living

## Meditation: unlocking the secret and science of happiness


``The Joy of Living`` is a path of meditation[^1] practice that is very easily to follow by you and focus in explaining it to modern world.

::: {.callout-note}
Meditation is a key-tool to master emotions, to understand negative and positive emotions, it empower and sharpen your real intelligence. Ultimatly, it is an esencial tool to understand your own mind.
:::


Meditation deals with basic functions of the mind and the movements toward inner peace and away from suffering.[^2]

## Goals

``The Joy of Living`` method contains **three goals**:

- Calming the Mind
- Opening the Heart
- Awakening Wisdom


**First**, calming the mind, in this level you will use any situation or experience, included negative emotions and painbody, as a gateway to inner peace.

**Second**, you are meditating how to open your heart to the world around you and decrease the self-fixation that lies at the root of negative emotions.

**Third**, in this level you will practise the insight meditation, a profound form of meditation that uproots the causes of negative emotions.

The goals of this tool included:

- How to rest in a state of spacious and alert presence using visual objects, sounds, tastes as support to transform negative emotions and painbody.
- How to deal with distractions and understand daily meditation, postures, lenght and to define a session.
- How negative emotions relate to fixate just in your wellbeing and positive mental states can grow.
- How to see beyond superficial thoughts and emotions and see things as they actually are, rather the mistaken version of reality that we project onto the world.


[^1]: [The Joy of Living: Unlocking the Secret and Science of Happiness](https://www.goodreads.com/book/show/289448.The_Joy_of_Living){.external}
[^2]: [What is the Joy of Living?](https://tergar.org/programs/what-is-the-joy-of-living/){.external}