
# MindValley

## Vishen Lakhiani and MindValley know the code

**You need to know the code**, as a engineer and programmer,*Vishen Lakhiani*, provides you with powerful tools to understand our negative emotions and mindset and how destructive they can be in the tech world we live. 

This **map** guides you how to break the code and achieve extraordinary results in life.

## Transcend the culturescape

<mark>First at all, our sorrounding culture may be a negative influence, that is, you must transcend the culturescape and question society’s bullshit rules.</mark>

As you move through life, you are constantly told what you should do or how you should live.

Our culture contains many outdated beliefs that dictate what kind of job and education you should have and how you should think and eat. Or weather, as an exemple, you need a college degree to guarantee success. Maybe you do not need a degree at all. Maybe you are in the wrong way. Update your believe, question it.

## Rewrite your models

Second, practice consciousness engineering and create self-encouraging models of reality.

Thus, you may need to <mark>rewrite your models of reality updating your mindset, that is, redefining what you think about yourself and how this triggers negative emotions.<mark>

## Upgrade your system for living

Third, /<mark>upgrade your system for living and be able to bend reality. This will lead you to a three-step approach of discovering, refreshing and measuring.</mark>

So the first step is to discover, you can do this by reading books, talking to people and exploring the world around you for inspiration. As an example, check mindvalley.com, guarantee you will find out lots of inspiration and what inspiration is.

Second, refresh regularly.

Third, measure how effective you are being.

Re-coding your mindset to get the ability to bend reality. That  means that you can hold onto your goals for the future while making sure that your inner peace is firmly rooted in the present by focusing on the here and now: make fun and happiness a key part of your daily life. 

## Create a vision

Fourth, practice *blissipline* and <mark>create a vision for their future.</mark>

*Blissipline* starts with gratitude. It has been scientifically proven that people have more energy and experience less depression when they practice gratitude.

The people making you feel guilty for going your own way and choosing your own life are simply saying:

>Look at me.
>
>I’m better than you because my chains are bigger.
>
>It takes courage to break those chains and define your own life.

So dare to live your precious days on Earth to their fullest, true to yourself, with open heart and thoughtful mind, and with the courage to change what doesn’t work and accept the consequences.

>You may find that you can fly farther than you ever imagined.


<mark>Reverse the froward gap. The forward gap is the distance between your present self and who you want to be. But the problem with focusing on the forward gap is that you are always keeping positive emotions out of you reach in the future and creating negative ones.</mark>

Never experiencing positive ones, instead, destructive emotions that destroy your execution day-by-day.

You should reverse the gap and look to your past to appreciate and be grateful for what you have achieved so far. This allows you to practice blissipline.

Crafting a vision is key for your future that corresponds with your inner peace. However, this vision can be dangerous if you confuse your vision with culturescape's vision.

## Be unfuckwithable

Fifth, be unfuckwithable and embrace your quest. Your motivation for reaching your vision must come from within; do  not seek validation from outside.

<mark>Be unfuckwithable. This means realizing that you depend only on yourself and that nothing anyone says or does can stop you from achieving your goals by having self-fueled goals that aren’t dependent upon others and realizing that only you have what it takes to be successful.</mark>

>It turns out that our brains are literally hardwired to perform at their best not when they are negative or even neutral, but when they are positive.
>
>Yet in today’s world, we ironically sacrifice happiness for success only to lower our brain’s success rates
>
>-- Shawn Achor


[^1]: [](){.external}
[^2]: [](){.external}