
# The power of now



The power of Now,
how stillness stops train of thoughts mind


Now, this new set of tools sign directly to the present moment, that is, do not allow your mind to travel to past and future and focus the now, the present moment. If your mind vagues a creates out of the present, your negative emotions would rise without control. Even with repetition or the culture of your enviroment it may create a pattern of thoughts-emotions.

Finally, it will avoid you to be present and having the amount of necessary energy to focus at the present moment and properly execute minor task or be creative. 

There is such a thing as old emotional pain living inside you. It is an accumulation of painful life experience that was not fully faced and accepted in the moment it arose. It leaves behind an energy form of emotional pain. It comes together with other energy forms from other instances, and so after some years you have a painbody, an energy entity consisting of old emotion. That is the painbody.

Eckhart Tolle's message is simple and strigthforward: living in the now is the truest path to positive emotions and fullfilment. And some several tools and portals help you to understand negative emotions. Basicly, the main idea is to stop the stream of thoughts in your mind using the different aproch of every tool, that is, a portal to silence, portals to review those destructive emotions and understand them.

The body, as an exemple, is an excelent portal to now: using your inner body as an anchor to the Now.
The gift of full attention and the power in the simple act of noticing

Besides defining what painbody exactly is this tool adds what painbody is concealing: your life's purpose (next lines are adapted from "The power of Now").

If you look within rather than only without, however, you discover that you have an inner and an outer purpose, and since you are a microcosmic reflection of the macrocosm, it follows that the universe too has an inner and outer purpose inseparable from yours.

The outer purpose of the universe is to create form and experience the interaction of forms—the play, the dream, the drama, or whatever you choose to call it.

Its inner purpose is to awaken to its formless essence. Then comes the reconciliation of outer and inner purpose: to bring that essence—consciousness—into the world of form and thereby transform the world.

The ultimate purpose of that transformation goes far beyond anything the human mind can imagine or comprehend.

To produce constructive emotions you need to clarify your inner and outer purpose; name it a vision, a big goal. Rise a family or start a company, but the lack of purpuse leaves you alone without shield in front of a lot of negative emotions produced by the absence of direcction.

[^1]: [](){.external}
[^2]: [](){.external}