
# Psychomagic



Pyschomagic,
custom poetic acts work symbolically


This highly practical and creative tool shows how psychological realizations can cause real transformation when manifested by concrete and custom poetic acts designed symbolically.

While living in Mexico, Alejandro Jodorowsky became familiar with the eccentric but effective cures provided by folk healers and how emotions and thoughts were interwoven with deep mental pain expressed as a disease. Your mind represents symbolically that pain produced by destructive emotions. In that point, it is blatant the power of destruction tha destructive emotions hold and how well the name "destructive emotions" is asigned.

As a result, it is easier for the unconscious to understand the language of dreams than that of rationality. Illness can even be seen as a physical dream that reveals unresolved emotional and psychological problems.

Psychomagic presents the shamanic and genealogical principles to create a healing therapy that could use the powers of dreams, art, and theater to empower you to heal wounds that in some cases had traveled through generations.

The concrete and often surreal poetic actions are part of an elaborate strategy intended to break apart the dysfunctional persona with whom you identify to connect with a deeper self.

That is when real transformation can manifest and heal the painbody, heal the negative and destructive emotions that block your life and get stuck and trapped in that dark point where emotions are you worst enemy and drain all your energy into more pain.

Therefore, there is no space for big constructive emotions, thus psychomagic may be the real key to unblock those negative emotions, understand their origin and, eventually, wipe out its power over you. 

Psychomagic takes the same elements associated with a negative emotional charge and recasts them in an action that will make them positive and enable them to pay the psychological debts hindering their lives.

“Birds born in a cage think flying is an illness.”
Alejandro Jodorowsky

Metagenealogy is a practical guide, a very useful tool, to recognizing and overcoming the patterns of negative and profound desctructive emotions and influences of the four generations before you. It explains the way how this particular and inherited painbody comes from the past and survives to the future being an organism within your mind that shapes your world's perception. The tool's goal is to uncover your family’s psychological heritage, heal negative emotion patterns of behavior and illness in your family tree, and let positive emotions emerge.

It explains how you are the result of several sorroundings pushing you: repetition of familial patterns from the past (negative emotions and painbody), the creation of new ideas from postive emotions from inner peace and society rules and punishments constraining you executed by family. 

It is an embodied sense of self that you inherit from at least four prior generations, constituting both a life-giving treasure and a deadly trap. You are both an heir of your lineage and a necessary variation that brings the family into new territory. Are you doomed to repeat the patterns of your parents and grandparents? Or can you harness your familial and individual talents to create your own destiny?

[^1]: [](){.external}
[^2]: [](){.external}