
# Silva Method


José Silva
silva method and alpha and altered state


José Silva was an electronics repairman who developed the formerly known as Silva Mind Control. Silva did research on the brain and various brain frequencies, this tool aims to reach and sustain a state of mental functioning, called alpha state, where brainwave frequency is seven to fourteen Hz: daydreaming and the transition to sleeping are alpha states.

With this tool, you will gain powerful positive and constructive solid emotions and habits and overcome negative emotions and its consequences (painbody, habits). It opens to increase your level of energy, free yourself from negative beliefs and behaviours, boost your creativity even learn to practise creative dreaming and awake intuition and inspiration.

The alpha brain state is active at your right hemisphere. You are in this state every day several times and it crucial understand how it works:

Every morning when you wake up (your mind passes from the theta brain state to the alpha and then to the beta).
You can use this time window to train yourself in the Silva Method and induced your mind into trance.
It is very important to learn how to enter and leave this brain state.
And you need to understand the alpha state boundaries.


"The discovery that human intelligence can learn to function, with awareness, at altered levels of mind, will go down in history as the greatest discovery of mankind.

It is sure to change our concepts of psychology, psychiatry, mind, and the subconscious."
jose silva

First, you must exercise every morning, for about fifty days, and while you count backwards you have to look, behind your closed eyelids, slightly above, that is 20 degree above the horizon. It is known that the brain produces alpha brainwaves when having your eyes at this position:

For ten days count backwards from 100 to 1 at a 2 seconds pace.
For the next ten days count backwards from 50 to 1 at the same pace.
For the following ten days count backwards from 25 to 1.
For the next ten days count from 10 to 1.
For the last ten days count from 5 to 1.

Second, you have to develop your very detailed visualization skill creating an imagery tool like a mental big black TV where you will project your visualizations. You need to practise to develop your visualization skill to focus entirely at a mental movie and try that irrelevant thoughts do not interrupt. As an example, in case you meditate before sleeping, you just confirm that you are going to have a night of restorative sleep.

Third, this is a mental movie you are going to play on your big flat mental TV:

Think one negative emotion o problem you can not solve. Keep it for minutes.
Imagine it solves by a basic and general solution. Visualize it in detail.
Recreate how it feels when the problem disappears, how it affects your family, and all the positive emotins related.

[^1]: [](){.external}
[^2]: [](){.external}