
# The Work

## The Work tool


>If a thought hurts, question it.  
>How?  
>Do your Work[^1]  

::: {.callout-note}
## Core idea the Word
The core idea where the work rests is very simple but powerful: <mark>when you believe your thoughts you suffer, but when I do not believe them you do not suffer, and that this is true for every human being.<mark>

**Freedom** is as simple as that. Upon this idea you can access to a very usefull tool of self-inquiry known as “*The Work*”.
:::


All the negative and suffering generated by ideas and the related destructive emotions that goes on inside our minds are not reality.[^3]

It’s just a story we torture ourselves with. *The Work* is a simple, completely replicable system for freeing ourselves of the thoughts and emotions that make us suffer. All war begins on paper, the war against those ideas and believes that drain your positive and constructive energy, for this reason, those ideas are the target of our war. 

**A thought is harmless unless we believe it**. It’s not our thoughts, but our attachment to our thoughts, that causes suffering. Attaching to a thought means believing that it’s true, without inquiring. A belief is a thought that we’ve been attaching to, often for years.

This tool is very easy to execute. You write down your stressful thoughts, and then ask yourself the following four questions.[^2]

## Question #1

**Question 1: Is it true?**

This question can change your life. Be still and ask yourself if the thought you wrote down is true.


## Question #2

**Question 2: Can you absolutely know it’s true?**

This is another opportunity to open your mind and to go deeper into the unknown, to find the answers that live beneath what we think we know.

## Question #3

**Question 3: How do you react—what happens—when you believe that thought?**

With this question, you begin to notice internal cause and effect. You can see that when you believe the thought, there is a disturbance that can range from mild discomfort to fear or panic. Make a list, and be specific.

## Question #4

**Question 4: Who would you be without the thought?**

Imagine yourself in the presence of that person (or in that situation), without believing the thought. How would your life be different if you could not even think the stressful thought? How would you feel? Which do you prefer—life with or without the thought? Which feels kinder, more peaceful?

## Turn around

**Turn the thought around**

The “turnaround” allows you to experience the opposite of what you believe. Once you have found one or more turnarounds to your original statement, you are invited to find at least three specific, genuine examples of how each turnaround is true in your life.


[^1]: [The Work](https://thework.com/){.external}
[^2]: [1-2-3 Sheet](https://thework.com/i-complain-about/){.external}
[^3]: [The Work is a Practice](https://thework.com/instruction-the-work-byron-katie/){.external}