
# Or Die

Emotions are bio-cultural mental states associated with the nervous system and the culture where you live. Emotions are central among with thoughts, feelings, physical and behavioural responses, and a degree of pleasure or displeasure, pain or relief.

Emotions produce different physiological, behavioural and cognitive changes and they are a very complex process where those systems play a relevant key-role but not yet fully defined.

Emotion is also linked to behavioural tendency. As an example, if you are an extroverted person you are more likely to be social and express your emotions, while if you are introverted one, your are more likely to be more socially withdrawn and conceal your emotions.

Therefore, emotion is often the driving force behind lots of behaviours, positive or negative, depending on the nature of emotion.

While the biological component of emotions is pretty clear, the cultural role is yet not well know but critical on some aspects:

inner culture related to your own identity and core family beliefs
as much as outer and social culture as well as cognitive bias and universal beliefs.

Then, all these components act at the very moment of building a single emotion:

biology and physiology
primary response
the structure itself of your brain
culture
inner culture
education and family traits,
level of energy
emotional background: painbody,
outer (and environmental) culture
cognitive bias
universal beliefs
country culture and language



Biology and Physiology

The joining between both components, biology and culture (inner and outer), is the emotion-building where the feeling is a key-bond together with the primary response (physical response as fight, fly, freeze, faint, etc..) which feedback on both ways constantly.

Between the sophisticated system which is a feeling and the biological and pyhsiological primary response there is the structure itself of your brain that shapes time and space.

Therefore, this framewrok of time and space stain the way your brain starts to elaborate thoughts and emotions,

Immanuel Kant tells us that space and time are the pure (a priori) forms of how we collect information from the outer. 

Intuition is contrasted with the conceptualization (or categorization. before you taint thoughts with your painbody, bias, family traits or beliefs) performed by the understanding, and involves the way in which we passively receive data through the external world. 

Physical sensation (before emotion) itself is the “matter” of intuition, but its “form” lies in us, as the way in which this data is organized.
Inner culture

It is crucial that you may differentiate feelings from emotions to understand the cultural background which conditions the whole process. And not only feelings but also affects and moods are different from emotions: emotion emerges from a elaborate process from a primary response to an external or internal stimulus.

A feeling is the subjective experience of emotional state once it has occurred, so every person feels in a particular way and it can not be possible to feel what other people fell. You may recreate or imagine but never feel the same emotions neither feelings.

The way you feel a concrete feeling rose by an emotion depends on how your mind builds it and a lot of factors from inner culture and the balance among them have a big influence:

your emotional education and family traits,
your level of energy from where you feel, 
your emotional background: painbody,

These factors define the way you feel an emotion, even it is a constructive or destructive one you may alter it completely. This interpretation and mental recreation have the power to modify deeply the meaning and direction of your reaction and consequently the behaviour that emerges from that moment.


Thus, study conscientiously the tools provided to you in chapter Two because they are key to land emotions in the safe ground and make possible you inner peace grows steadily towards positive emotions if not destructive emotions will not a mere reaction but a context and background which helps to build new emotions with a negative approach at the very beginning:

Pyschomagic by Alejandro Jodorowsky will help you with your emotional education and family traits,
David Dawkins scale will show you the level of energy from where you feel,
Eckhart Tolle speaks a lot about your emotional background: painbody, and gives innumerable bits of advice to cope with it, as well as Byron Katie among others,

Emotion is a mental state and the deep nature of it is bio-cultural. 
As we will see in Chapter Four, the biological and physical part have very practical tools to deal with: health, diet, exercise and so on.


However, it is very difficult to differentiate inner and outer culture because both of them are feedbacking each other constantly in several ways. The outer depends much more on the interaction of people and it is very reactive at each exchange.

"What we feel is a choice." 
Piyush Shrivastav
Furthermore, outer culture is linked to the vast diversity of cultures and languages that exist on our planet and it creates a huge complexity.

Let's see how environment and outer culture affect the way you feel, the way emotion is built by your mind.

As you see, emotions are a tailor-made big-scale built by you depending on such so-called inner and outer culture factors for each circumstance, always variable and unstable. Emotions are, as we all know very volatile.

Outer culture


The outer cultural elements that configure your environment are these three backgrounds:

culture create cognitive bias,  
universal beliefs,
particular culture from linguistics, that is, what language you talk and how many languages you know.


Cognitive biases are the no-logical errors that arise in your line of reasoning when you make a decision. This judgment is flawed by personal beliefs highly influenced by the cultural environment. You share this bias with a lot of people of your country, continent, cultural tradition or same language speakers.

Your brain absorbs huge quantities of information during the day. Some of this information we consciously think about.

But as the conscious part of the brain can only be the focus on one thing at a time, your brain is looking for shortcuts to help you make decisions and do not get stuck. These mental unconscious shortcuts often fail to produce a correct judgment, and the result is cognitive biases.

"You'll never cross an emotional bridge, if you keep rushing back to the other side.” 
T.F. Hodge


The most important types of biases are overconfidence, self-serving, herd mentality, loss aversion, framing cognitive, narrative fallacy, anchoring and confirmation.

The cognitive biases and universal beliefs could be erased if you use the tools provided in Chapter Two by Vishen Lakhiani and Bryon Katie.

In any case, the list of cognitive biases and universal beliefs is almost infinite. Every minute they boost negative emotions and drain lots of energy so the work here is listing all the bias and beliefs and one-by-one with the tools provided you should learn how they operate. And doing this you has wakled the first and most dificult step. With understandig and acceptance you will annihilate the power they own over you.

List of universal beliefs:

I need to know what to do.
I don’t know what to do.
I know what is best for others.
I know what is best for myself.
Something terrible is going to happen.
It’s possible to make a mistake.
People should not lie.
People should respect me.
I can control how others feel about me.
I feel your energy.
I need more money.
Life isn’t fair.
Parents should love their children.
Children should love their parents.
I need to make a decision.
I can’t do anything right.
I can disappoint people.
I don’t want to look foolish.
There’s too much to do.
There’s not enough time.
I know what you need.
I am worthless.
It’s my job to make you happy.
I need a partner to be happy.It’s my fault.
I should be different.
I need to be careful in life.

After cognitive biases and universal beliefs, you may turn to the vocabulary and words you usually use because they create the way your ideas are and therefore how emotions are delivered.

As an exemple, these words are not universal and neither the emotions which they describe: boredom, nostalgia, amae, sprezzatura, nonchalance, baraka and mokita. Let's see someone.

"Nostalgia" was coined in 1688 by Johannes Hofer as "mal du pays", that is "homesickness". Symptoms were also thought to include fainting, high fever, indigestion, stomach pain, and death. Nowadays this word means somethig different and very far from it was created.



From Japanese tradition, the concept of "amae" is about being in harmony with others and being able to depend on them as a child could depend on their parents. Even though a child can act ridiculous, their parents would indulge them.

"Sprezzatura" is an Italian word defined as "a certain nonchalance, so as to conceal all art and make whatever one does or says appear to be without effort and almost without any thought about it". It is the ability of the courtier to display "an easy facility in accomplishing difficult actions which hides the conscious effort that went into them".

The word "Mokita" is a fantastic word taken from a language called Kivila. It is spoken in Papua New Guinea. The best translation you can get of Mokita is, “the truth we all know but agree not to talk about.”

"Baraka" is an ancient Sufi word, which can be translated as "a blessing, or as the breath, or essence of life from which the evolutionary process unfolds."

In France, if you describe someone as "nonchalant", you mean that they appear not no worry or care about things and that they seem very calm.

Summing up, you have seen a lot of components which act at the very moment of building a single emotion:

biology and physiology
primary response
the structure itself of your brain
culture
inner culture
education and family traits,
level of energy
emotional background: painbody,
outer and environmental culture
cognitive bias
universal beliefs
country culture and linguistics


So, the outcome of your body and brain when you feel something is a mix of several factors interacting in various ways. 

This final feeling is a representation of a situation, and a bad reading on that situation conditioned by bad readings of the past may be fatal. 

This process of reading situations and react and record information through time form your identity.


Identity


Speaking about the process of building emotion, all the factors pointed converge in that concluding concept: identity.

Your identity is shaped by all the living past in the form of emotions, thoughts, concepts, philosophies, logics and body scars.

The main obstacle to respond from inner peace and constructive emotions and not with negative and destructive ones is your attachment to your identity, whatever form is in whenever moment you evaluate.  

Following what has been seen so far, the reason why you are attached to your identity is an emotion. 

To be safe.

Your brain enjoys a big gift from evolution: the imperative and urgent drive to be safe, thanks to it you are alive.

Your evolved brain has got inner powerful structures as the reptilian complex and the limbic or paleomammalian system that watch out constantly any form of threat. It does by notices in the form of negative emotions (subtle or strong), independently the thread is real or not.

So there is an inner system very useful but at the same time very dangerous for your inner peace.

The most important skill to understand emotions and not be killed by them is to remain in silence. That is, inner peace. Have you a lot or little. Nevermind. This is the second most difficult task.

To open a little space of calm and silence (even the tynest) to allow you to watch out these subtle and strong notices, it does not matter if they are real or not as log as a truck is not going to run over you. Open that space, that meditation, that insight. Even if it is the most painful moment of your life. Do it. Best at moment. If not, later. Maybe fourty year later, do not worry, they are waiting for you.

Watching out these negative emotions as destructive ones and track them to their origin at the core of your identity and then, once there, your must do the most difficult task: change.

Kill it. By understanding how it works and how it is incardinated on your identity. It does not matter if it is at core itself or your identity or at border, if it is your family identity or your country identity, if it is your damaged identiy or your winner identity. Kill it.

There is no tie. Either you kill it changing and evolving your way to look the world and life or your identity will kill you turning you in a zombie, that is, a deatch person that can move its body and barely speaks.

Kill and be alive o die being alive as a zombie. There is no other output. Everyday. Ever moment. Every emotion.