

# Identity

## Building who you are


<mark>Speaking about the process of building emotion, all the factors pointed converge in that concluding concept: **identity**.</mark>

Your identity is shaped by all the living past in the form of emotions, thoughts, concepts, philosophies, logics and body scars.

::: {.callout-note}
## Defining the main obstacle
The main obstacle to respond from inner peace and constructive emotions and not with negative and destructive ones is your attachment to your identity, whatever form is in whenever moment you evaluate.  
:::

Following what has been seen so far, the reason why you are attached to your identity is an emotion, or better expressed, <mark>a infinite collection of them transformed into feelings and creating another time new emotions and so on.</mark>

There are two fundamental drivers behind positve and negative emotions: *transgression* and *safety*.

## To be safe

::: {.callout-note}
## Be safe
Your brain enjoys a big gift from evolution: the imperative and urgent drive to be safe[^1], thanks to it you are alive.
:::

Your evolved brain has got inner powerful structures as the reptilian complex and the limbic or paleomammalian system that watch out constantly any form of threat. It does by notices in the form of *negative emotions* (subtle or strong), independently the thread is real or not.

>Don't be careful.  
>You could hurt yourself.  
>
>-- Byron Katie

So there is an inner system very useful but at the same time very dangerous for your inner peace.

The most important skill to understand emotions and not be killed by them is <mark>to remain in silence.</mark> That is, **inner peace**. Have you a lot or little. Nevermind. This is the second most difficult task.

## Transgression

<mark>To open a little space of calm and silence (even the tynest) to allow you to watch out these subtle and strong notices, it does not matter if they are real or not as log as a truck is not going to run over you. Open that space, that meditation, that insight. Even if it is the most painful moment of your life. Do it. Best at moment. If not, later. Maybe fourty year later, do not worry, they are waiting for you.</mark>

Watching out these negative emotions as destructive ones and track them to their origin at the core of your identity and then, once there, your must do the most difficult task: **change**.

Kill it

By understanding how it works and how it is incardinated on your identity. It does not matter if it is at core itself or your identity or at border, if it is your family identity or your country identity, if it is your damaged identiy or your winner identity.

Kill it.

There is no tie. Either you kill it changing and evolving your way to look the world and life or your identity will kill you turning you in a zombie, that is, a deatch person that can move its body and barely speaks.

**Kill and be alive o die being alive as a zombie. There is no other output. Everyday. Ever moment. Every emotion.**


[^1]: [Safety, Threat, and Stress in Intergroup Relations: A Coalitional Index Model ](https://pubmed.ncbi.nlm.nih.gov/26177946/){.external}