
# Inner Culture

## Feelings and emotions

It is crucial that you may differentiate feelings from emotions[^1] to understand the **cultural background which conditions the whole process**.

And not only feelings but also affects and moods are different from emotions: <mark>emotion emerges from a elaborate process from a primary response to an external or internal stimulus.</mark>


:::{.callout-note}
## Feeling
A feeling is the <mark>subjective experience of emotional state once it has occurred, so every person feels in a particular way and it can not be possible to feel what other people fell.</mark>
:::

You may *recreate* or imagine but never feel the same emotions neither feelings.

## Your feelings are unique

The way you feel a concrete feeling rose by an emotion **depends on how your mind builds it** and a lot of factors from inner culture and the balance among them have a big influence:

- your emotional education and family traits,
- your level of energy from where you feel, 
- your emotional background: painbody,

These factors define *the way you feel an emotion*, even it is a constructive or destructive one, you may alter it completely. This interpretation and mental recreation have the power to modify deeply the meaning and direction of your reaction and consequently the behaviour that emerges from that moment.


Thus, study conscientiously the tools provided to you in [part Two](/part2/YouCanWin.qmd#tools-cheatsheet) because they are <mark>key to land emotions in the safe ground and make possible you inner peace grows steadily towards positive emotions if not destructive emotions will not a mere reaction but a context and background which helps to build new emotions with a negative approach</mark> at the very beginning:

- Pyschomagic by *Alejandro Jodorowsky* will help you with your emotional education and family traits,
- *David Dawkin*s scale will show you the level of energy from where you feel,
- *Eckhart Tolle* speaks a lot about your emotional background: painbody, and gives innumerable bits of advice to cope with it, as well as *Byron Katie* among others.


## What you feel is a choice

Emotion is a mental state and the deep nature of it is bio-cultural. 
As we will see in [Part Four](/part4/SoAction.qmd), the biological and physical part have very practical tools to deal with: health, diet, exercise and so on.

However, it is very difficult to differentiate inner and outer culture because both of them are intervowen and feedbacking each other constantly in several ways. The outer depends much more on the interaction of people and it is very reactive at each exchange.

>What we feel is a choice.
>
>-- Piyush Shrivastav

Furthermore, outer culture is linked to the vast diversity of cultures and languages that exist on our planet and it creates a huge complexity.

Let's see how environment and outer culture affect the way you feel, the way emotion is built by your mind.

As you see, emotions are a <mark>tailor-made big-scale built by you depending on such so-called inner and outer culture factors for each circumstance, always variable and unstable.</mark> Emotions are, as we all know very volatile.



[^1]: [The Difference Between Feelings and Emotions](https://counseling.online.wfu.edu/blog/difference-feelings-emotions/){.external}
