---
Title: "Pain exists"
---


# Pain exists

## The numbers do not lie

The National Science Foundation[^1] release time ago this shocking number, an average person has about 10,000 to 60,000 thoughts per day. Of those, 80% are negative and the most, almost 100% are repetitive ones.[^2] Instead, Queen’s University researchers discovered we have more than 6,000 thoughts each day[^3].

Well, perhaps the number is inaccurate, let's say it is 10,000, highly enough? 

::: {.callout-note}
## Fact
The fact is that those thoughts are creating an imaginary and brutal drama in your mind. These repetitive thoughts are creating a **negative pattern and but still, they are triggering an entire universe of emotions** related to each thought: it would be amazing if it were not terrible.
:::


Remember, if you are not aware of them, they will stop whispering and start shouting. They will grow until collapse your life, health either wealth, probably both of them.  

The list is endless: fears, trauma, insecurities, present, past and future losses, failures, broken hearts and more and more fears.

## A living organism

Your lack of awareness of this process is literally feeding a living organism within your mind who is colonizing your brain, your health, your body and finally your wealth.

When this happens the consequences are known. <mark>No more energy for sex, or creativity. No more ideas to create a start-up, quit your boring job or love your family. </mark> 

Your entire life and energy goes to this organism: the ``pain-body``[^4].

It shapes your identity so far and you will eventually die for it. Your life will hopelessly bend to this side, suddenly you will see that your external life reflects your internal mind. Your day-by-day life will mirror your mind and it will not be a surprise that all your friends share their negative thoughts and failures with you.

## Just, Watch it

Then, your conversations will turn about sad stories, bad things and dark futures. You are feeding the inner monster, no healthy diet, no more exercise, no more sex, no more right sleep, no more creative job.

>Watch your thoughts; >they become words.  
>Watch your words; they become actions.  
> Watch your actions; they become habit.  
> Watch your habits; they become character.  
>Watch your character; it becomes your destiny.  
> 
>-- Lao Tzu


You did it, ``your inner energy is not unlimited``: <mark>you choose between feed your inner monster either your inner peace.</mark> Yes, I understand that inner peace concept is boring but each minute you give it to your inner gang, you take it from your life. From your peace. Literally.
 

[^1]: [National Science Foundation](https://www.nsf.gov/){.external}
[^2]: [Fear of the unknown: One fear to rule them all?](https://www.sciencedirect.com/science/article/pii/S0887618516300469){.external}
[^3]: [Brain meta-state transitions demarcate thoughts across task contexts exposing the mental noise of trait neuroticism](https://www.nature.com/articles/s41467-020-17255-9){.external}
[^4]: [The Painbody: Endure it or Walk Away?](https://eckharttolle.com/the-painbody-endure-it-or-walk-away-2/){.external}