
# So, Action

## Decision making

>It is the same with people as it is with riding a bike.  
>Only when moving can one comfortably maintain one’s balance.
>
>-- Albert Einstein

This well-known quote from **Albert Einstein** reflects faithfully how your brain works: <mark>if you cease on your work to terminate negative emotions, then multiple and new forms of destructive emotions will emerge with new variations of old ones.</mark>

This process will reinforce old patterns and [painbody](/part2/PowerNow.qmd#painbody) (inner and outer culture) and its power over you and your identity will eventually gain the dark side that painful lives perfectly know.

On the contrary, more work, more constructive emotions you get, the prize undoubtedly worths it. **Decision making** is key in this equation and it can not set aside.

If you feel a <mark>huge amount of energy is draining from somewhere, stop and go deep to the roots, and then, **take action**.</mark>

## Taking action

Taking action will come with this pack, I assure you:

- It will very painful and blocking, it will hurt like hell: **do not run away**, 
- it will take a long time from decision making to take action until it is fully solved: **do not hurry up,**
- it will very difficult and tough: do not give up. **Rest some time, but do not give up**.

:::{.callout-note}
## Life is not a picnic
Life is not a picnic and you are not a girl or a boy, right? If you feel so bad, you are on the right path. Feeling bad is a fundamental part of being an adult. Choose the right tool. Work. That is all. Take action.
:::

If instead, you do not feel a huge amount of energy is draining but there is some fog and discomfort around you, then, there is a solution: **take action!**

>Whatever it happens, the main idea is easy:  
>if your doubt is between doing either not-doing,   
>always choose to do. 

## Doubts? Take action!

I will repeat and explain the idea if you are stuck, doubtful and questioning both sides of the question and it is not clear. **Stop thinking**. Between doing either not-doing, always choose to do. Because:

- If it goes right, save yourself that useless thinking time,
- If not, you will learn, remember, fail fast, life is not a picnic.

If you feel that *fog*, somehow discomfort, some bad feelings but nothing more, your must go, <mark>take action and work, exercise, run, sing, write and whatever you do through that discomfort: do whatever you do with discomfort.</mark>

I promise you that action will kill it. Therefore, to solve the problems that negative emotions carry  you need:

- **Energy**, you have it, you are alive. Use it to grow inner peace killing negative emotions by understanding them.
- **Tools**, read this book. 
- **Action** (discipline and focus). Life is not a picnic and you are an adult. Forget *Disneyland* now. So, action!

:::{.callout-note}
## Old fake emotions
<mark>If you do not take action, you will not feel emotions. You will *recreate* old emotions.<mark>[^1]

If life is within you, you will create new ones.

Those fake ones hide real emotions, real pain and real inner peace. You will live with that mental fog which chains you to **fake negative emotions**.

You will live **sentimentality**, in full self-deception, in false comfort.
:::


>Identity loves to splash around in the shit thinking it is real life, but no.


Remember, you are moving without pedalling and life feels good, but it means you and your bike are mountains down .. backwards. Is it necessary that I explain how it finishes?

How to differentiate  real emotions from sentimentality? Easy, you, your identity and your life change. Once you feel it, never forget. Life is unforgettable. 



[^1]: [Sentimentality is Unearned Emotion, Elliot Slaughter ](https://elliottslaughter.com/2021/06/sentimentality){.external}

